name: CI/CD Pipeline

on:
  workflow_dispatch:   # allow Slack/API to trigger
  push:
    branches:
      - app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Build
        run: echo "íº€ CI/CD pipeline started on branch ${{ github.ref }}"
